#!/usr/bin/env bash
# Build a lightweight codebase context cache for agents to read instead of
# scanning raw files. Produces .ship-context/ with four markdown files totalling
# ~800-1500 tokens. No LLM calls — pure shell/grep/git.
#
# Usage:
#   bash scripts/build-context.sh [/path/to/project]
#
# Cache invalidation: skips rebuild if HEAD commit hash hasn't changed.
# Force a rebuild: bash scripts/build-context.sh --force
#
# Output:
#   .ship-context/INDEX.md        ← repo overview, languages, entry points
#   .ship-context/structure.md    ← directory tree with per-file descriptions
#   .ship-context/symbols.md      ← functions, classes, exports (grep-based)
#   .ship-context/recent-changes.md ← recent git log + diff stat
set -euo pipefail

FORCE=0
PROJECT_DIR=""
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    *)       PROJECT_DIR="$arg" ;;
  esac
done
PROJECT_DIR="${PROJECT_DIR:-$PWD}"
PROJECT_DIR="$(cd "$PROJECT_DIR" && pwd)"

OUT="$PROJECT_DIR/.ship-context"
CACHE_KEY_FILE="$OUT/.cache-key"

mkdir -p "$OUT"

# Cache check: skip if HEAD hasn't changed and --force not given
CURRENT_HEAD="$(git -C "$PROJECT_DIR" rev-parse HEAD 2>/dev/null || echo "no-git")"
if [ "$FORCE" -eq 0 ] && [ -f "$CACHE_KEY_FILE" ]; then
  CACHED_HEAD="$(cat "$CACHE_KEY_FILE" 2>/dev/null || true)"
  if [ "$CACHED_HEAD" = "$CURRENT_HEAD" ]; then
    echo "[build-context] Context cache is current (HEAD: ${CURRENT_HEAD:0:8}) — skipping rebuild."
    exit 0
  fi
fi

echo "[build-context] Building codebase context for: $PROJECT_DIR"

# ── INDEX.md ─────────────────────────────────────────────────────────────────
REPO_NAME="$(basename "$PROJECT_DIR")"

# Detect languages by file extension presence
LANGS=""
[ -n "$(find "$PROJECT_DIR" -maxdepth 4 -name "*.py" -not -path "*/.git/*" -not -path "*/node_modules/*" 2>/dev/null | head -1)" ] && LANGS="$LANGS Python"
[ -n "$(find "$PROJECT_DIR" -maxdepth 4 -name "*.ts" -not -path "*/.git/*" -not -path "*/node_modules/*" 2>/dev/null | head -1)" ] && LANGS="$LANGS TypeScript"
[ -n "$(find "$PROJECT_DIR" -maxdepth 4 -name "*.js" -not -path "*/.git/*" -not -path "*/node_modules/*" 2>/dev/null | head -1)" ] && LANGS="$LANGS JavaScript"
[ -n "$(find "$PROJECT_DIR" -maxdepth 4 -name "*.go" -not -path "*/.git/*" 2>/dev/null | head -1)" ] && LANGS="$LANGS Go"
[ -n "$(find "$PROJECT_DIR" -maxdepth 4 -name "*.rs" -not -path "*/.git/*" 2>/dev/null | head -1)" ] && LANGS="$LANGS Rust"
[ -n "$(find "$PROJECT_DIR" -maxdepth 4 -name "*.sh" -not -path "*/.git/*" 2>/dev/null | head -1)" ] && LANGS="$LANGS Shell"
LANGS="${LANGS# }"  # trim leading space

# Entry points
ENTRY_POINTS=""
for ep in package.json setup.py pyproject.toml Cargo.toml go.mod CLAUDE.md README.md; do
  [ -f "$PROJECT_DIR/$ep" ] && ENTRY_POINTS="${ENTRY_POINTS}
- $ep"
done
ENTRY_POINTS="${ENTRY_POINTS#
}"

# CLAUDE.md summary (first 10 non-blank lines)
CLAUDE_SUMMARY=""
if [ -f "$PROJECT_DIR/CLAUDE.md" ]; then
  CLAUDE_SUMMARY="$(grep -v '^\s*$' "$PROJECT_DIR/CLAUDE.md" | head -10 2>/dev/null || true)"
fi

cat > "$OUT/INDEX.md" <<EOF
# Codebase Index: $REPO_NAME

> Generated by build-context.sh — read this before exploring the repo.
> Check structure.md for file layout, symbols.md for key definitions.

## Overview
- **Repo:** $REPO_NAME
- **Languages:** ${LANGS:-unknown}
- **HEAD:** ${CURRENT_HEAD:0:12}
- **Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date +%Y-%m-%dT%H:%M:%SZ)

## Entry points
${ENTRY_POINTS:-None detected}

## Project instructions (CLAUDE.md excerpt)
${CLAUDE_SUMMARY:-No CLAUDE.md found}

## Navigation
- **structure.md** — directory tree with per-file descriptions
- **symbols.md** — functions, classes, exports across the codebase
- **recent-changes.md** — last 20 commits and recent diff stats

## Key directories
EOF

# Add top-level directories
find "$PROJECT_DIR" -maxdepth 1 -mindepth 1 -type d \
  -not -name ".git" \
  -not -name "node_modules" \
  -not -name ".ship-context" \
  -not -name ".agent-runs" \
  -not -name "__pycache__" \
  -not -name ".venv" \
  -not -name "venv" \
  -not -name "dist" \
  -not -name "build" \
  | sort | while read -r dir; do
    echo "- $(basename "$dir")/"
  done >> "$OUT/INDEX.md"

echo "[build-context] Written: INDEX.md"

# ── structure.md ─────────────────────────────────────────────────────────────
cat > "$OUT/structure.md" <<'EOF'
# Directory Structure

> One line per file. Size in bytes. First comment/docstring line where available.
> Excludes: .git, node_modules, __pycache__, .venv, dist, build, .ship-context

EOF

find "$PROJECT_DIR" \
  -not -path "*/.git/*" \
  -not -path "*/node_modules/*" \
  -not -path "*/__pycache__/*" \
  -not -path "*/.venv/*" \
  -not -path "*/venv/*" \
  -not -path "*/dist/*" \
  -not -path "*/build/*" \
  -not -path "*/.ship-context/*" \
  -not -path "*/.agent-runs/*" \
  -not -path "*/.pytest_cache/*" \
  -not -path "*/.mypy_cache/*" \
  -type f \
  \( -name "*.py" -o -name "*.ts" -o -name "*.js" -o -name "*.sh" \
     -o -name "*.go" -o -name "*.rs" -o -name "*.md" -o -name "*.json" \
     -o -name "*.yaml" -o -name "*.yml" -o -name "*.toml" \) \
  | sort | while read -r f; do
    rel="${f#$PROJECT_DIR/}"
    size="$(wc -c < "$f" 2>/dev/null || echo 0)"
    # grab first meaningful comment or docstring line
    hint="$(grep -m1 -E '^\s*(#|//|/\*|"""|\x27\x27\x27|<!--)' "$f" 2>/dev/null \
      | sed 's/^\s*[#/*"!<-]*\s*//' | cut -c1-80 || true)"
    if [ -n "$hint" ]; then
      printf '%-60s %6d  %s\n' "$rel" "$size" "$hint"
    else
      printf '%-60s %6d\n' "$rel" "$size"
    fi
  done >> "$OUT/structure.md"

echo "[build-context] Written: structure.md"

# ── symbols.md ───────────────────────────────────────────────────────────────
cat > "$OUT/symbols.md" <<'EOF'
# Key Symbols

> Functions, classes, and exports extracted by grep (no LLM).
> Format: file:line  definition

EOF

{
  # Python: def, class, async def
  grep -rn --include="*.py" -E "^(def |class |async def )" "$PROJECT_DIR" \
    --exclude-dir=".git" --exclude-dir="__pycache__" \
    --exclude-dir=".venv" --exclude-dir="venv" \
    --exclude-dir=".ship-context" --exclude-dir=".agent-runs" \
    2>/dev/null | sed "s|$PROJECT_DIR/||" | head -200 || true

  # TypeScript/JavaScript: export function, export class, export const, export default
  grep -rn --include="*.ts" --include="*.js" \
    -E "^export (default |async )?(function|class|const|let|var|type|interface)" "$PROJECT_DIR" \
    --exclude-dir=".git" --exclude-dir="node_modules" \
    --exclude-dir=".ship-context" --exclude-dir=".agent-runs" \
    2>/dev/null | sed "s|$PROJECT_DIR/||" | head -200 || true

  # Shell: function declarations
  grep -rn --include="*.sh" -E "^[a-zA-Z_][a-zA-Z0-9_]*\(\)" "$PROJECT_DIR" \
    --exclude-dir=".git" --exclude-dir=".ship-context" --exclude-dir=".agent-runs" \
    2>/dev/null | sed "s|$PROJECT_DIR/||" | head -100 || true

  # Go: func declarations
  grep -rn --include="*.go" -E "^func " "$PROJECT_DIR" \
    --exclude-dir=".git" --exclude-dir=".ship-context" \
    2>/dev/null | sed "s|$PROJECT_DIR/||" | head -200 || true

  # Rust: pub fn, pub struct, pub enum
  grep -rn --include="*.rs" -E "^pub (fn|struct|enum|trait|type)" "$PROJECT_DIR" \
    --exclude-dir=".git" --exclude-dir=".ship-context" \
    2>/dev/null | sed "s|$PROJECT_DIR/||" | head -200 || true
} >> "$OUT/symbols.md"

echo "[build-context] Written: symbols.md"

# ── recent-changes.md ────────────────────────────────────────────────────────
cat > "$OUT/recent-changes.md" <<EOF
# Recent Changes

> Last 20 commits and diff stats. Use this to understand what's been touched recently.

## Last 20 commits
EOF

git -C "$PROJECT_DIR" log --oneline -20 2>/dev/null >> "$OUT/recent-changes.md" || echo "(no git history)" >> "$OUT/recent-changes.md"

printf '\n## Diff stat (last 5 commits)\n' >> "$OUT/recent-changes.md"
git -C "$PROJECT_DIR" diff --stat HEAD~5 HEAD 2>/dev/null >> "$OUT/recent-changes.md" || echo "(not enough history)" >> "$OUT/recent-changes.md"

printf '\n## Currently modified (uncommitted)\n' >> "$OUT/recent-changes.md"
git -C "$PROJECT_DIR" status --short 2>/dev/null >> "$OUT/recent-changes.md" || echo "(no git status)" >> "$OUT/recent-changes.md"

echo "[build-context] Written: recent-changes.md"

# ── Cache key ────────────────────────────────────────────────────────────────
echo "$CURRENT_HEAD" > "$CACHE_KEY_FILE"

# ── Token estimate ───────────────────────────────────────────────────────────
TOTAL_WORDS="$(wc -w "$OUT"/INDEX.md "$OUT"/structure.md "$OUT"/symbols.md "$OUT"/recent-changes.md 2>/dev/null | tail -1 | awk '{print $1}')"
TOTAL_TOKENS=$(( TOTAL_WORDS * 100 / 75 ))
echo "[build-context] Done. Context cache: ~${TOTAL_TOKENS} tokens across 4 files."
if [ "$TOTAL_TOKENS" -gt 3000 ]; then
  echo "[build-context] WARNING: context cache is large (${TOTAL_TOKENS} tokens). Consider using --force after trimming large generated files."
fi
