#!/usr/bin/env bash
# check-drift.sh — plan anti-drift checker
#
# Compares the approved plan.md against implementation-log.md and git state
# to surface structural drift before the verify agent runs.
#
# Usage:
#   bash scripts/check-drift.sh /path/to/project
#
# Expects:
#   $PROJECT_DIR/.agent-runs/latest-run.txt  — path to the active run folder
#   $RUN_DIR/plan.md                         — approved plan
#   $RUN_DIR/implementation-log.md           — coder's log (optional)
#
# Writes:
#   $RUN_DIR/drift-report.md
#
# Exit codes:
#   0  always (caller uses || true — drift report is informational, not blocking)
set -euo pipefail

PROJECT_DIR="${1:-$PWD}"

# ── Locate run folder ─────────────────────────────────────────────────────────
LATEST_RUN_TXT="$PROJECT_DIR/.agent-runs/latest-run.txt"
if [ ! -f "$LATEST_RUN_TXT" ]; then
  echo "[check-drift] No .agent-runs/latest-run.txt found — skipping drift check."
  exit 0
fi

REL_RUN="$(cat "$LATEST_RUN_TXT" 2>/dev/null | tr -d '\r' | head -n1)"
if [ -z "$REL_RUN" ]; then
  echo "[check-drift] latest-run.txt is empty — skipping."
  exit 0
fi

RUN_DIR="$PROJECT_DIR/$REL_RUN"
PLAN_FILE="$RUN_DIR/plan.md"
IMPL_LOG="$RUN_DIR/implementation-log.md"
REPORT="$RUN_DIR/drift-report.md"

if [ ! -f "$PLAN_FILE" ]; then
  echo "[check-drift] No plan.md found in $RUN_DIR — skipping."
  exit 0
fi

# ── Helpers ───────────────────────────────────────────────────────────────────

# Extract lines within a markdown section (## Header) up to the next ## header.
# Usage: section_lines "## Section Name" <file>
section_lines() {
  local header="$1"
  local file="$2"
  awk -v hdr="$header" '
    $0 == hdr { in_section=1; next }
    in_section && /^## / { exit }
    in_section { print }
  ' "$file" 2>/dev/null || true
}

# ── Check 1: Unchecked acceptance criteria ────────────────────────────────────
UNCHECKED_LINES=""
UNCHECKED_COUNT=0
if grep -q "^- \[ \]" "$PLAN_FILE" 2>/dev/null; then
  UNCHECKED_LINES="$(grep "^- \[ \]" "$PLAN_FILE")"
  UNCHECKED_COUNT="$(echo "$UNCHECKED_LINES" | grep -c "^- \[ \]" || echo 0)"
fi

# ── Check 2: Files listed in plan but not changed ─────────────────────────────
# Extract backtick-quoted filenames from the "Files likely to change" section.
PLAN_FILES=""
if grep -q "^## Files likely to change" "$PLAN_FILE" 2>/dev/null; then
  PLAN_FILES="$(section_lines "## Files likely to change" "$PLAN_FILE" \
    | grep -oE '\`[^`]+\`' | tr -d '`' | sort -u || true)"
fi

FILES_MISSING_FROM_GIT=""
if [ -n "$PLAN_FILES" ]; then
  CHANGED_FILES="$(git -C "$PROJECT_DIR" diff --name-only HEAD 2>/dev/null \
    | sort -u || true)"
  # Also include staged and unstaged
  CHANGED_STAGED="$(git -C "$PROJECT_DIR" diff --cached --name-only 2>/dev/null \
    | sort -u || true)"
  ALL_CHANGED="$(printf '%s\n%s\n' "$CHANGED_FILES" "$CHANGED_STAGED" | sort -u | grep -v '^$' || true)"
  while IFS= read -r pf; do
    [ -z "$pf" ] && continue
    # Match basename or full path suffix
    BASENAME="$(basename "$pf")"
    if ! echo "$ALL_CHANGED" | grep -qF "$BASENAME" && \
       ! echo "$ALL_CHANGED" | grep -qF "$pf"; then
      FILES_MISSING_FROM_GIT="${FILES_MISSING_FROM_GIT:+$FILES_MISSING_FROM_GIT
}- $pf"
    fi
  done <<< "$PLAN_FILES"
fi

# ── Check 3: Files changed but not mentioned in plan ─────────────────────────
FILES_OUTSIDE_PLAN=""
CHANGED_ALL="$(git -C "$PROJECT_DIR" diff --name-only HEAD 2>/dev/null || true)"
if [ -n "$CHANGED_ALL" ] && [ -n "$PLAN_FILES" ]; then
  while IFS= read -r cf; do
    [ -z "$cf" ] && continue
    BASENAME="$(basename "$cf")"
    # Skip run-folder artifacts — those are always expected
    if echo "$cf" | grep -qE "^\.agent-runs/"; then continue; fi
    if ! echo "$PLAN_FILES" | grep -qF "$BASENAME" && \
       ! echo "$PLAN_FILES" | grep -qF "$cf"; then
      FILES_OUTSIDE_PLAN="${FILES_OUTSIDE_PLAN:+$FILES_OUTSIDE_PLAN
}- $cf"
    fi
  done <<< "$CHANGED_ALL"
fi

# ── Check 4: Self-reported deviations ────────────────────────────────────────
DEVIATIONS=""
if [ -f "$IMPL_LOG" ]; then
  DEVIATIONS="$(section_lines "## Deviations from approved plan" "$IMPL_LOG" \
    | grep -v "^\s*$" | head -20 || true)"
fi

# ── Determine verdict ─────────────────────────────────────────────────────────
VERDICT="CLEAN"
if [ "$UNCHECKED_COUNT" -gt 0 ]; then
  VERDICT="FAIL"
elif [ -n "$FILES_MISSING_FROM_GIT" ] || [ -n "$FILES_OUTSIDE_PLAN" ] || [ -n "$DEVIATIONS" ]; then
  VERDICT="WARN"
fi

# ── Write report ──────────────────────────────────────────────────────────────
cat > "$REPORT" <<REPORTEOF
# Drift Report

Generated by \`check-drift.sh\` — zero LLM cost, pure shell comparison of plan.md vs implementation state.

## Drift check: ${VERDICT}

$(if [ "$VERDICT" = "FAIL" ]; then
  echo "> **FAIL**: Acceptance criteria from plan.md are unchecked. Verify should REQUEST CHANGES."
elif [ "$VERDICT" = "WARN" ]; then
  echo "> **WARN**: Unexpected scope or self-reported deviations detected. Verify should scrutinize flagged files."
else
  echo "> **CLEAN**: All acceptance criteria checked, no unexpected files, no self-reported deviations."
fi)

### Unchecked acceptance criteria

$(if [ "$UNCHECKED_COUNT" -gt 0 ]; then
  echo "These items in plan.md ## Acceptance criteria are still unchecked:"
  echo ""
  echo "$UNCHECKED_LINES"
else
  echo "None — all acceptance criteria are ticked."
fi)

### Files in plan but not changed

$(if [ -n "$FILES_MISSING_FROM_GIT" ]; then
  echo "These files were listed in plan.md ## Files likely to change but were not touched:"
  echo ""
  echo "$FILES_MISSING_FROM_GIT"
else
  echo "None — all planned files were touched (or no file list in plan)."
fi)

### Files changed but not in plan

$(if [ -n "$FILES_OUTSIDE_PLAN" ]; then
  echo "These files were changed but not listed in plan.md ## Files likely to change:"
  echo ""
  echo "$FILES_OUTSIDE_PLAN"
else
  echo "None — no unexpected files changed."
fi)

### Self-reported deviations

$(if [ -n "$DEVIATIONS" ]; then
  echo "The coder reported these deviations in implementation-log.md:"
  echo ""
  echo "$DEVIATIONS"
else
  echo "None — implementation-log.md ## Deviations section is empty."
fi)
REPORTEOF

echo "[check-drift] Drift check: ${VERDICT} — report written to $REPORT"

exit 0
