#!/usr/bin/env bash
# Set up Telegram notifications for the Agentic Ship Kit.
#
# Run this once on your machine:
#   bash scripts/setup-telegram.sh
#
# What you need first:
#   1. A Telegram bot token  — message @BotFather on Telegram, send /newbot
#   2. Your chat ID          — message @userinfobot on Telegram, it replies with your ID
set -euo pipefail

CONFIG="$HOME/.agentic-ship-telegram"

echo "=== Agentic Ship Kit — Telegram Setup ==="
echo ""

# Load existing config if present
EXISTING_TOKEN=""
EXISTING_CHAT_ID=""
if [ -f "$CONFIG" ]; then
  # shellcheck disable=SC1090
  source "$CONFIG" 2>/dev/null || true
  EXISTING_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
  EXISTING_CHAT_ID="${TELEGRAM_CHAT_ID:-}"
fi

# Bot token
if [ -n "$EXISTING_TOKEN" ]; then
  echo "Existing bot token found: ${EXISTING_TOKEN:0:10}..."
  read -r -p "Press Enter to keep it, or paste a new token: " INPUT_TOKEN
  TOKEN="${INPUT_TOKEN:-$EXISTING_TOKEN}"
else
  echo "Step 1: Get your bot token"
  echo "  → Open Telegram, message @BotFather, send /newbot"
  echo "  → Copy the token it gives you (looks like: 123456:ABCdef...)"
  echo ""
  read -r -p "Paste your bot token: " TOKEN
fi

TOKEN="$(echo "$TOKEN" | tr -d '[:space:]')"
if [ -z "$TOKEN" ]; then
  echo "No token entered. Exiting." >&2
  exit 1
fi

# Chat ID
if [ -n "$EXISTING_CHAT_ID" ]; then
  echo ""
  echo "Existing chat ID found: $EXISTING_CHAT_ID"
  read -r -p "Press Enter to keep it, or paste a new chat ID: " INPUT_CHAT_ID
  CHAT_ID="${INPUT_CHAT_ID:-$EXISTING_CHAT_ID}"
else
  echo ""
  echo "Step 2: Get your chat ID"
  echo "  → Open Telegram, message @userinfobot"
  echo "  → It will reply with your ID (a number, may be negative for groups)"
  echo ""
  read -r -p "Paste your chat ID: " CHAT_ID
fi

CHAT_ID="$(echo "$CHAT_ID" | tr -d '[:space:]')"
if [ -z "$CHAT_ID" ]; then
  echo "No chat ID entered. Exiting." >&2
  exit 1
fi

# Test the connection
echo ""
echo "Testing connection..."
RESPONSE="$(curl -s -X POST \
  "https://api.telegram.org/bot${TOKEN}/sendMessage" \
  -d "chat_id=${CHAT_ID}&text=✅ Agentic Ship Kit connected! You will receive task alerts here." \
  2>&1)"

if echo "$RESPONSE" | grep -q '"ok":true'; then
  echo "✅ Test message sent successfully!"
else
  echo "❌ Failed to send test message. Check your token and chat ID."
  echo "Response: $RESPONSE"
  exit 1
fi

# Save config
cat > "$CONFIG" <<EOF
# Agentic Ship Kit — Telegram config
# Generated by setup-telegram.sh
# Keep this file private — it contains your bot token.
TELEGRAM_BOT_TOKEN="$TOKEN"
TELEGRAM_CHAT_ID="$CHAT_ID"
EOF
chmod 600 "$CONFIG"

echo ""
echo "Config saved to: $CONFIG"

# ── Check / install Claude Code CLI ─────────────────────────────────────────
echo ""
echo "Checking for Claude Code CLI..."

CLAUDE_STATUS=""
CLAUDE_VERSION=""

if command -v claude >/dev/null 2>&1; then
  CLAUDE_VERSION="$(claude --version 2>/dev/null | head -1 || echo "unknown version")"
  CLAUDE_STATUS="ok"
  echo "Claude Code CLI found: $CLAUDE_VERSION"
else
  echo "Claude Code CLI not found. Installing via npm..."
  CLAUDE_STATUS="installing"
  # Send Telegram notice before the install (may take a minute)
  curl -s -X POST "https://api.telegram.org/bot${TOKEN}/sendMessage" \
    --data-urlencode "chat_id=${CHAT_ID}" \
    --data-urlencode "text=Installing Claude Code CLI — this takes about a minute..." \
    >/dev/null 2>&1 || true

  if command -v npm >/dev/null 2>&1; then
    if npm install -g @anthropic-ai/claude-code 2>&1; then
      if command -v claude >/dev/null 2>&1; then
        CLAUDE_VERSION="$(claude --version 2>/dev/null | head -1 || echo "unknown version")"
        CLAUDE_STATUS="ok"
        echo "Claude Code CLI installed: $CLAUDE_VERSION"
      else
        CLAUDE_STATUS="install-failed"
        echo "Install ran but claude still not found. Try: npm install -g @anthropic-ai/claude-code"
      fi
    else
      CLAUDE_STATUS="install-failed"
      echo "npm install failed. Try manually: npm install -g @anthropic-ai/claude-code"
    fi
  else
    CLAUDE_STATUS="no-npm"
    echo "npm not found. Install Node.js first: https://nodejs.org"
    echo "Then run: npm install -g @anthropic-ai/claude-code"
  fi
fi

# ── Send full status report to Telegram ─────────────────────────────────────
PROJECTS_LINE="No projects registered yet. Run: bash scripts/register-project.sh /path/to/project myname"
if [ -f "$HOME/.agentic-ship-projects" ] && [ -s "$HOME/.agentic-ship-projects" ]; then
  PROJECTS_LINE="$(cat "$HOME/.agentic-ship-projects")"
fi

case "$CLAUDE_STATUS" in
  ok)
    CLAUDE_LINE="Claude Code CLI: $CLAUDE_VERSION"
    READY_LINE="Ready! Start the listener: bash scripts/poll-telegram.sh &"
    ;;
  installing)
    CLAUDE_LINE="Claude Code CLI: still installing..."
    READY_LINE="Re-run setup once install finishes."
    ;;
  install-failed)
    CLAUDE_LINE="Claude Code CLI: install failed — run: npm install -g @anthropic-ai/claude-code"
    READY_LINE="Fix the install, then start: bash scripts/poll-telegram.sh &"
    ;;
  no-npm)
    CLAUDE_LINE="Claude Code CLI: npm not found — install Node.js from https://nodejs.org"
    READY_LINE="Install Node.js and npm, then: npm install -g @anthropic-ai/claude-code"
    ;;
esac

curl -s -X POST "https://api.telegram.org/bot${TOKEN}/sendMessage" \
  --data-urlencode "chat_id=${CHAT_ID}" \
  --data-urlencode "text=Agentic Ship Kit — Setup Complete

${CLAUDE_LINE}

Registered projects:
${PROJECTS_LINE}

${READY_LINE}

Commands you can send once the listener is running:
/ship <project> <task>
/projects
/status
/stop
/help" \
  >/dev/null 2>&1 || true

echo ""
echo "Status report sent to Telegram."
echo ""
if [ "$CLAUDE_STATUS" = "ok" ]; then
  echo "Everything is ready. Start the listener:"
  echo "  bash scripts/poll-telegram.sh &"
else
  echo "Fix the Claude Code CLI install (see above), then start the listener:"
  echo "  bash scripts/poll-telegram.sh &"
fi
