#!/usr/bin/env bash
# Set up Telegram notifications for the Agentic Ship Kit.
#
# Run this once on your machine:
#   bash scripts/setup-telegram.sh
#
# What you need first:
#   1. A Telegram bot token  — message @BotFather on Telegram, send /newbot
#   2. Your chat ID          — message @userinfobot on Telegram, it replies with your ID
set -euo pipefail

CONFIG="$HOME/.agentic-ship-telegram"

echo "=== Agentic Ship Kit — Telegram Setup ==="
echo ""

# Load existing config if present
EXISTING_TOKEN=""
EXISTING_CHAT_ID=""
if [ -f "$CONFIG" ]; then
  # shellcheck disable=SC1090
  source "$CONFIG" 2>/dev/null || true
  EXISTING_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
  EXISTING_CHAT_ID="${TELEGRAM_CHAT_ID:-}"
fi

# Bot token
if [ -n "$EXISTING_TOKEN" ]; then
  echo "Existing bot token found: ${EXISTING_TOKEN:0:10}..."
  read -r -p "Press Enter to keep it, or paste a new token: " INPUT_TOKEN
  TOKEN="${INPUT_TOKEN:-$EXISTING_TOKEN}"
else
  echo "Step 1: Get your bot token"
  echo "  → Open Telegram, message @BotFather, send /newbot"
  echo "  → Copy the token it gives you (looks like: 123456:ABCdef...)"
  echo ""
  read -r -p "Paste your bot token: " TOKEN
fi

TOKEN="$(echo "$TOKEN" | tr -d '[:space:]')"
if [ -z "$TOKEN" ]; then
  echo "No token entered. Exiting." >&2
  exit 1
fi

# Chat ID
if [ -n "$EXISTING_CHAT_ID" ]; then
  echo ""
  echo "Existing chat ID found: $EXISTING_CHAT_ID"
  read -r -p "Press Enter to keep it, or paste a new chat ID: " INPUT_CHAT_ID
  CHAT_ID="${INPUT_CHAT_ID:-$EXISTING_CHAT_ID}"
else
  echo ""
  echo "Step 2: Get your chat ID"
  echo "  → Open Telegram, message @userinfobot"
  echo "  → It will reply with your ID (a number, may be negative for groups)"
  echo ""
  read -r -p "Paste your chat ID: " CHAT_ID
fi

CHAT_ID="$(echo "$CHAT_ID" | tr -d '[:space:]')"
if [ -z "$CHAT_ID" ]; then
  echo "No chat ID entered. Exiting." >&2
  exit 1
fi

# Test the connection
echo ""
echo "Testing connection..."
RESPONSE="$(curl -s -X POST \
  "https://api.telegram.org/bot${TOKEN}/sendMessage" \
  -d "chat_id=${CHAT_ID}&text=✅ Agentic Ship Kit connected! You will receive task alerts here." \
  2>&1)"

if echo "$RESPONSE" | grep -q '"ok":true'; then
  echo "✅ Test message sent successfully!"
else
  echo "❌ Failed to send test message. Check your token and chat ID."
  echo "Response: $RESPONSE"
  exit 1
fi

# Save config
cat > "$CONFIG" <<EOF
# Agentic Ship Kit — Telegram config
# Generated by setup-telegram.sh
# Keep this file private — it contains your bot token.
TELEGRAM_BOT_TOKEN="$TOKEN"
TELEGRAM_CHAT_ID="$CHAT_ID"
EOF
chmod 600 "$CONFIG"

echo ""
echo "Config saved to: $CONFIG"
echo ""
echo "Telegram notifications are now active."
echo "You will receive alerts when:"
echo "  → Claude finishes making a plan (needs your approval)"
echo "  → Tests pass or fail"
echo "  → Review is complete (APPROVE / REQUEST CHANGES / BLOCK)"
echo "  → The session needs to be resumed"
echo ""
echo "To trigger tasks from Telegram, also run:"
echo "  bash scripts/poll-telegram.sh &"
echo "  (or add it to your startup: see scripts/poll-telegram.sh for instructions)"
